# Generated by Django 6.0.4 on 2026-04-17 18:40

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_default=django.db.models.expressions.RawSQL('uuidv7()', []), editable=False, primary_key=True, serialize=False),
        ),
    ]
