# Generated by Django 6.0.4 on 2026-04-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
