# Generated by Django 6.0.4 on 2026-04-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
