# Generated by Django 6.0.4 on 2026-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_sample_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sample_size',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_id',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='core_profil_gender_2b6106_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age_group'], name='core_profil_age_gro_b545f6_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country_id'], name='core_profil_country_519e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age'], name='core_profil_age_b743af_idx'),
        ),
    ]
